In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_info_df = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [3]:
# Get a brief summary of the crowdfunding_info DataFrame.
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   blurb                    1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_at              1000 non-null   int64
 11  deadline                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(7), object(6)
memory usage: 103.6+ KB

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
- A "category_id" column that is numbered sequential form 1 to the length of the number of unique categories.
- A "category" column that has only the categories.

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
- A "subcategory_id" column that is numbered sequential form 1 to the length of the number of unique subcategories.
- A "subcategory" column that has only the subcategories. 

Export the DataFrame as a `subcategory.csv` CSV file.

In [4]:
# Get the crowdfunding_info_df columns.
crowdfunding_info_df_cols = crowdfunding_info_df.columns.tolist()
crowdfunding_info_df_cols

['cf_id',
 'contact_id',
 'company_name',
 'blurb',
 'goal',
 'pledged',
 'outcome',
 'backers_count',
 'country',
 'currency',
 'launched_at',
 'deadline',
 'staff_pick',
 'spotlight',
 'category & sub-category']

In [5]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df['category'], crowdfunding_info_df['subcategory'] = crowdfunding_info_df['category & sub-category'].str.split('&', 1, expand=True)
crowdfunding_info_df['category'], crowdfunding_info_df['subcategory'] = crowdfunding_info_df['category & sub-category'].str.split('/', 1).str
crowdfunding_info_df.head()

C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\3326114668.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  crowdfunding_info_df['category'], crowdfunding_info_df['subcategory'] = crowdfunding_info_df['category & sub-category'].str.split('&', 1, expand=True)
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\3326114668.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  crowdfunding_info_df['category'], crowdfunding_info_df['subcategory'] = crowdfunding_info_df['category & sub-category'].str.split('/', 1).str
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\3326114668.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  crowdfunding_info_df['category'], crowdfunding_info_df['subcategory'] = crowdfunding_info_df['category & sub-category'].str.split('/', 1).str

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [6]:
# Get the unique categories and subcategories in separate lists.
categories = crowdfunding_info_df['category'].unique()
subcategories = crowdfunding_info_df['subcategory'].unique()
print(categories)
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']
['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [7]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(categories))
print(len(subcategories))

9
24

In [8]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [9]:
# Use a list comprehension to add "cat" to each category_id. 
cat = 'cat{}'
cat_ids = [cat.format(c) for c in category_ids]
# Use a list comprehension to add "subcat" to each subcategory_id.    
scat = 'subcat{}'
scat_ids = [scat.format(s) for s in subcategory_ids]
    
print(cat_ids)
print(scat_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9']
['subcat1', 'subcat2', 'subcat3', 'subcat4', 'subcat5', 'subcat6', 'subcat7', 'subcat8', 'subcat9', 'subcat10', 'subcat11', 'subcat12', 'subcat13', 'subcat14', 'subcat15', 'subcat16', 'subcat17', 'subcat18', 'subcat19', 'subcat20', 'subcat21', 'subcat22', 'subcat23', 'subcat24']

In [10]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame({"category_id": cat_ids, "category": categories})
# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
subcategory_df = pd.DataFrame({"subcategory_id": scat_ids, "subcategory": subcategories})

In [11]:
category_df

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video
5        cat6    publishing
6        cat7         games
7        cat8   photography
8        cat9    journalism

In [12]:
subcategory_df

   subcategory_id        subcategory
0         subcat1        food trucks
1         subcat2               rock
2         subcat3                web
3         subcat4              plays
4         subcat5        documentary
5         subcat6     electric music
6         subcat7              drama
7         subcat8         indie rock
8         subcat9          wearables
9        subcat10         nonfiction
10       subcat11          animation
11       subcat12        video games
12       subcat13             shorts
13       subcat14            fiction
14       subcat15  photography books
15       subcat16   radio & podcasts
16       subcat17              metal
17       subcat18               jazz
18       subcat19       translations
19       subcat20         television
20       subcat21       mobile games
21       subcat22        world music
22       subcat23    science fiction
23       subcat24              audio

In [13]:
# Export categories_df and subcategories_df as CSV files.
category_df.to_csv("Resources/category.csv", index=False)

subcategory_df.to_csv("Resources/subcategory.csv", index=False)

### Campaign DataFrame
----
**Create a Campaign DataFrame that has the following columns:**
- The "cf_id" column.
- The "contact_id" column.
- The “company_name” column.
- The "blurb" column is renamed as "description."
- The "goal" column.
- The "goal" column is converted to a `float` datatype.
- The "pledged" column is converted to a `float` datatype. 
- The "backers_count" column. 
- The "country" column.
- The "currency" column.
- The "launched_at" column is renamed as "launch_date" and converted to a datetime format. 
- The "deadline" column is renamed as "end_date" and converted to a datetime format.
- The "category_id" with the unique number matching the “category_id” from the category DataFrame. 
- The "subcategory_id" with the unique number matching the “subcategory_id” from the subcategory DataFrame.
- And, create a column that contains the unique four-digit contact ID number from the `contact.xlsx` file.
 

Then export the DataFrame as a `campaign.csv` CSV file.

In [14]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [15]:
# Rename the blurb, launched_at, and deadline columns.
campaign_df = campaign_df.rename(columns={'blurb': "description",
                           'launched_at': "launch_date",
                           'deadline': "end_date"
                           })

In [16]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df['goal'] = campaign_df['goal'].astype(float)
campaign_df['pledged'] = campaign_df['pledged'].astype(float)
campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [17]:
# Check the datatypes
campaign_df.dtypes

cf_id                        int64
contact_id                   int64
company_name                object
description                 object
goal                       float64
pledged                    float64
outcome                     object
backers_count                int64
country                     object
currency                    object
launch_date                  int64
end_date                     int64
staff_pick                    bool
spotlight                     bool
category & sub-category     object
category                    object
subcategory                 object
dtype: object

In [18]:
# Format the launch_date and end_date columns to datetime format
from datetime import datetime as dt
campaign_df['launch_date'] = pd.to_datetime(campaign_df["launch_date"], unit='s').dt.strftime('%Y-%m-%d')
campaign_df['end_date'] = pd.to_datetime(campaign_df["end_date"], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays

In [19]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = pd.merge(pd.merge(campaign_df, category_df, how = "outer", on = ['category']), 
                              subcategory_df, how = "outer", on = ['subcategory'])


campaign_merged_df.tail(10)

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory,category_id,subcategory_id
990,399,5983,"Dixon, Perez and Banks",Re-engineered encompassing definition,8300.0,2111.0,failed,57,CA,CAD,2021-12-29,2022-01-16,False,False,photography/photography books,photography,photography books,cat8,subcat15
991,1378,2873,Clements Ltd,Persistent bandwidth-monitored framework,3700.0,1343.0,failed,52,US,USD,2020-07-07,2021-07-27,False,False,photography/photography books,photography,photography books,cat8,subcat15
992,806,2961,Walter Inc,Streamlined 5thgeneration intranet,10000.0,8142.0,failed,263,AU,AUD,2020-12-20,2021-01-31,False,False,photography/photography books,photography,photography books,cat8,subcat15
993,1563,3043,"Sanders, Farley and Huffman",Cross-group clear-thinking task-force,172000.0,55805.0,failed,1691,US,USD,2021-04-08,2021-12-18,True,False,photography/photography books,photography,photography books,cat8,subcat15
994,1951,6013,Rodriguez-Robinson,Ergonomic methodical hub,5900.0,4997.0,failed,114,IT,EUR,2021-07-23,2021-11-25,False,True,photography/photography books,photography,photography books,cat8,subcat15
995,461,3521,Erickson-Rogers,De-engineered even-keeled definition,9800.0,7608.0,canceled,75,IT,EUR,2021-07-03,2021-07-08,False,True,photography/photography books,photography,photography books,cat8,subcat15
996,1095,3565,Young and Sons,Innovative disintermediate encryption,2400.0,4596.0,successful,144,US,USD,2020-11-28,2021-02-28,False,False,journalism/audio,journalism,audio,cat9,subcat24
997,1388,4517,Valenzuela-Cook,Total incremental productivity,6700.0,7496.0,successful,300,US,USD,2021-01-04,2021-10-04,False,False,journalism/audio,journalism,audio,cat9,subcat24
998,2448,2389,Little Ltd,Decentralized bandwidth-monitored ability,6900.0,12155.0,successful,419,US,USD,2021-01-25,2021-04-18,False,False,journalism/audio,journalism,audio,cat9,subcat24
999,602,2153,Giles-Smith,Right-sized web-enabled intranet,9700.0,11929.0,successful,331,US,USD,2022-02-01,2022-02-16,False,False,journalism/audio,journalism,audio,cat9,subcat24

In [20]:
# Drop unwanted columns
campaign_cleaned = campaign_merged_df.drop(['category & sub-category', 'category', 'subcategory', 'staff_pick', 'spotlight'], axis=1, inplace=True)

In [21]:
# Export the DataFrame as a CSV file. 
campaign_merged_df.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [22]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=2)
contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [23]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
dict_values = []


# Print out the list of values for each row.
print(dict_values)

[]

In [ ]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.

In [ ]:
# Check the datatypes.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [24]:
# Create a copy of the contacts_info_df DataFrame 
contact_info_df_copy = contact_info_df
contact_info_df_copy.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

In [25]:
# Convert row to column header in DataFrame
header_row = contact_info_df_copy.iloc[0]
contact_info_df_copy = pd.DataFrame(contact_info_df_copy.values[1:], columns=header_row)
contact_info_df_copy.head()

0                                                                               contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

In [26]:
# Extract the four-digit contact ID number.
contact_info_df_copy['contact_id'] = contact_info_df_copy['contact_info'].str.extract('(\d{4})')
contact_info_df_copy.head()

,contact_info,contact_id
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199

In [27]:
# Check the datatypes.
contact_info_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [28]:
# Convert the "contact_id" column to an int64 data type.
contact_info_df_copy['contact_id'] = contact_info_df_copy['contact_id'].astype('int64')
contact_info_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [29]:
# Extract the name of the contact and add it to a new column
contact_info_df_copy['name'] = contact_info_df_copy['contact_info'].str.extract('(\w[A-Za-z]*\W[A-Z]\w*)')
contact_info_df_copy.head()

,contact_info,contact_id,name
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz

In [30]:
# Extract the email from the contacts and add the values to a new column.
# contact_info_df_copy['email'] = contact_info_df_copy['contact_info'].str.extract('("email":\s\W[a-z]\w*\.*\W[a-z]\w*\@*\W[a-z]\w*\.*\w{2,})')
# contact_info_df_copy['email'] = contact_info_df_copy['contact_info'].str.extract('("email":\s\W[a-z]\w*\.*\W[a-z]\w*\@*\W[a-z]\w*\.*\w{2,})')
contact_info_df_copy['email'] = contact_info_df_copy['contact_info'].str.extract('([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)')
contact_info_df_copy.head()

,contact_info,contact_id,name,email
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco,cecilia.velasco@rodrigues.fr
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis,mariana.ellis@rossi.org
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods,sofie.woods@riviere.com
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti,jeanette.iannotti@yahoo.com
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz,samuel.sorgatz@gmail.com

In [31]:
contact_info_df_copy_df = pd.DataFrame({"contact_id": contact_info_df_copy['contact_id'], "name": contact_info_df_copy['name'], "email":contact_info_df_copy['email']})

df = contact_info_df_copy_df
pd.set_option('display.max_rows', df.shape[0]+1)

print(df)

     contact_id                    name  \
0          4661         Cecilia Velasco
1          3765           Mariana Ellis
2          4187             Sofie Woods
3          4941       Jeanette Iannotti
4          2199          Samuel Sorgatz
5          5650            Socorro Luna
6          5889         Carolina Murray
7          4842              Kayla Moon
8          3280          Ariadna Geisel
9          5468         Danielle Ladeck
10         3064        Tatiana Thompson
11         4904         Caleb Benavides
12         1299            Sandra Hardy
13         5602            Lotti Morris
14         5753         Reinhilde White
15         4495             Kerry Patel
16         4269          Sophie Antoine
17         2226           Martha Girard
18         1558          Stephanie King
19         2307           Amanda Palmer
20         2900             Lina Alcala
21         5695            Itzel Murphy
22         5708           Filippo Parry
23         1663            Katelyn Cole
24         3605             Brian Novak
25         4678               Cilly Gay
26         2251          Yolanda Snyder
27         6202         Evelin Odonnell
28         3715           Ingeborg Alba
29         4242           Marina Madrid
30         4326          Sheila Goodwin
31         5560            Valeria Rich
32         4002          Dustin Camacho
33         3813         Amalia Marenzio
34         5336               Gian Long
35         4994            Stewart Hunt
36         1471              Greca Ruiz
37         4482          Gerald Olivera
38         3241       Jaqueline Wallace
39         3477               John Lane
40         2265               Pero Joly
41         5911             Chad Turner
42         2288             Adam Zavala
43         4064            Tyler Rivera
44         1294             Jens Graham
45         5008        Virginia Caetani
46         3604          Martino Wagner
47         3263            Martin Meyer
48         5631        Marguerite Walls
49         2851              Peter Vogt
50         3714      Nicholas Christian
51         1664          Susi Steinberg
52         5027        Tammy Ramazzotti
53         3070            Abdul Thomas
54         4248          Justin Luxardo
55         2034          Antonio Gibson
56         4085            Jeremy Gomez
57         3569       Raymond Solorzano
58         3889            Flora Harris
59         3136             Cheryl Boyd
60         2103              Rhys Leiva
61         2329          Mariano Prieto
62         3325        Laurie Fibonacci
63         3131           David Rudolph
64         4995              Bryan Ross
65         3631            Ubaldo Brown
66         5373         Clelia Faulkner
67         3126           Sara Erickson
68         2194            Rupert Valle
69         2906         Puccio Kitzmann
70         2611       Thomas Hutchinson
71         2374         Abelardo Castro
72         3254            Greco Walker
73         3571         Miranda Lacombe
74         2812       Diana Schuchhardt
75         3961             Stacey Knox
76         3872             Glen Faivre
77         4736           Andrew Torres
78         5119             Denny Fritz
79         5725          Martyn Caldera
80         4037          Abigail Foster
81         2109         Anthony Hauffer
82         3283           Roger Gerlach
83         6181     Christopher Poirier
84         3251           Branka Traore
85         3443          Briana Etienne
86         2988           Brandon Olson
87         1673         Celia Ungaretti
88         2085         Barbara Guibert
89         1672            Daniela Bell
90         4426          Phyllis Gurule
91         3211        Alejandra Joseph
92         3190        Giulio Bohlander
93         2081            Amber Weller
94         3185             Mary Etzold
95         5044             Amy Georges
96         1883         Jennifer Giraud
97         2067           Rosie Peltier
98         4604             Oreste Ward
99         3203            Luis Edwards
100        5758         Fiona Griffiths
101        5755              Sally Raya
102        5150     Carolyn Charpentier
103        4181        Nathalie Alvarez
104        3006            Abril Lowery
105        4865         Ottone Sullivan
106        2862       Esmeralda Sollima
107        6070       Silvia Gierschner
108        5300         Kyle Cunningham
109        3486         Anel Carpentier
110        5989             Sarah Davis
111        2849              Luke Klein
112        1612          Gudrun Mueller
113        3307          Melissa Canali
114        5288         Gabrielle Ayala
115        6026           Laura Buckley
116        2212          Wilfrido Lorch
117        4591           Robert Bruder
118        2771           Phillip Soliz
119        5682              Alex Smith
120        5368        Jessica Martinez
121        3706            Kelly Carter
122        4034              Ahmad Sosa
123        3209         Toralf Iglesias
124        2384          Irene Anichini
125        3074          Alicia Cainero
126        2031            Tracey Laboy
127        5873          Donald Reynaud
128        5501     Venancio Stadelmann
129        3489            Seth Olivier
130        4210            Dennis Boaga
131        6151            Pedro Wilson
132        6047         Roland Weihmann
133        5445         Hector Morrison
134        5493        Evangelos Peters
135        6036        Gerardo Hamilton
136        2368          Meta Cuzzocrea
137        1501            Alma Raymond
138        4351       Kathleen Solimena
139        3096        Zacharie Cordier
140        6162             Riza Techer
141        1433         Enrique Guillen
142        2720           Tristan Weeks
143        5251           Natalie Lerma
144        1797            Rodney Hamon
145        1656      Adalberto Lombardo
146        1346       Florencia Querini
147        2989            Liam Rolland
148        5629               Ian Kelly
149        3456              Mehdi Todd
150        3229       Rembrandt Liguori
151        2277         Irmi Schweitzer
152        1276           Gioffre Stein
153        3694        Frida Villarreal
154        2260         Steffen Mangold
155        5374             Elias Marin
156        4420          Roman Gonzalez
157        3849         Reina Middleton
158        1638            Sandro Moran
159        5230          Gebhard Thanel
160        1763       Antonino Bolander
161        4323          Karl Trevisani
162        5256       Silvester Brookes
163        4836           Octavio Pratt
164        5981           Rebecca Greer
165        1463         Pierina Gaggini
166        4577          Robin Schleich
167        4951           Sergio Abbott
168        3567          Gilberto Evans
169        5475           James Elliott
170        2114        Timoteo Bolnbach
171        5216          Tonino Stanley
172        1665     Margaretha Murialdo
173        6051           Bianca Drubin
174        3983         Kaylee Hoffmann
175        2966         Teresa Vecellio
176        4478          Emine Tacchini
177        4238             Dawn Cortez
178        4404           Emily Cundari
179        5666            Eleanor Hall
180        3691      Monique Delgadillo
181        2703          Arnaude Warner
182        4253            Jason Howell
183        5652       Nicole Mccullough
184        3279       Rosmarie Esquibel
185        3233         Leonor Ferreira
186        3017             Brett Jones
187        3482               Nino Bien
188        2166              Jemma Tate
189        4146            Denis Rogers
190        2651             Vanesa Khan
191        1409          Victoria Ojeda
192        3717          Eugenio Martin
193        3963             Nancy Hayes
194        2152              Lara Jacob
195        2974          Gino Hernandez
196        1268        Vicente Tijerina
197        1822       Michele Brambilla
198        5066            Dana Ritacca
199        5075       Mitchell Bachmann
200        3855            Vincenza Key
201        5923       Salvador Gaillard
202        1867            Diane Rogner
203        4376           Josette Laine
204        2785         Courtney Fiebig
205        5884           Hugues Oliver
206        2441        Espartaco Willis
207        1243            Flavia Yoder
208        3411            Casey Flores
209        2467          Calogero Cross
210        1850           Charles Begum
211        2604           Adina Pollard
212        1693            Natasha Lara
213        2969          Benita Pottier
214        1544      Elizabeth Valdivia
215        4149             Mattia Huet
216        3463             Geza Howard
217        2939        Lauren Guillaume
218        2202           Joanna Baxter
219        1728              Tracy Metz
220        5362             Birgit Pena
221        4840         Elvira Papafava
222        2955          Ernest Delorme
223        5354          Christy Grossi
224        3847        Hermelinda Olmos
225        3025          Herbert Fraser
226        1615      Giancarlo Heydrich
227        5154     Constance Maldonado
228        5005       Giampiero Carlier
229        1349           Carlo Jacquot
230        3670          Gabriel Robles
231        2912              Gerd Gunpf
232        4336          Ashley Hellwig
233        5576           Patrick Rosas
234        2736           Lilla Leonard
235        3321            Tony Nicolas
236        3353       Allegra Benedetti
237        2336          Camille Tafuri
238        4369            Juan Wheeler
239        4464        Leopoldo Johnson
240        5626         Dietmar Grenier
241        1669           Leonid Scholl
242        5544        Olivie Contarini
243        6078         Jeffery Lacroix
244        2580        Edeltraud Chavez
245        3592            Mesut Morvan
246        4914         Gregory Jackson
247        3848            Nicola Rossi
248        2619           Eddie Collazo
249        4605        Philippe Gardner
250        6147                 Roy Fox
251        1383        Heiderose Garcia
252        1757         Claudine Rowley
253        4390             Astrid Roht
254        4165         Auguste Burnett
255        4529        Pellegrino Allen
256        6084           Angela Bowers
257        2916        Michael Descamps
258        2005       Heidelore Kennedy
259        2261           Lucrezia Koch
260        5342            Ivan Accardo
261        4087          Karen Avogadro
262        2761         Laetitia Gallet
263        2908          Amico Gosselin
264        2155            Ilaria Bowen
265        5642           Marlen Coardi
266        6217        Rafael Alexander
267        4222           Herma Gabbana
268        4798        Zachary Vespucci
269        5660         Marisol Richard
270        5000           Joseph Glover
271        2809           Lauretta Neal
272        3349          Simone Sauvage
273        3647           Ramona Brooks
274        5745         Gioele Schwital
275        2583           Elena Jimenez
276        5441              Pam Vargas
277        2090          Alison Morales
278        3386             Marc Aumann
279        1816            Carla Butler
280        4718           Dionigi Bruce
281        1677             Frank Henry
282        4218              Brent Pons
283        4548        Patricia Liebelt
284        1431        Micheletto Sykes
285        2830              Rose Blanc
286        4400           Vincent Singh
287        5773           Jamie Peacock
288        4161          Giorgia Dijoux
289        2062       Serena Piacentini
290        3458          Dimitri Posada
291        3174         Alexa Barillaro
292        5565              Megan Kuhl
293        1906       Kaitlyn Farinelli
294        5479    Jonathan Castellitto
295        4320           Lisa Terragni
296        4213      Olivier Petrucelli
297        3373           Jos Trobbiani
298        4184           Mirjam Dawson
299        5472          Javier Tessier
300        5559         Mirjana Collins
301        5419    Vanessa Tschentscher
302        4171           Antonina Cobb
303        1302          Bernard Durand
304        3520           Corey Greggio
305        6010       Rodolfo Couturier
306        4617         Pierre Cardenas
307        1417            Romeo Surian
308        4770              Ivo Moreno
309        4328          Federico Marie
310        5171            Maggie Boito
311        4394          Brianna Hanson
312        1794         Heiko Bourgeois
313        3510           Benito Gritti
314        2487              Mitzy Junk
315        2215           Samantha Lowe
316        4136          Ernesto Nerger
317        3723          Melinda Canova
318        5842        Mohammad Hartung
319        3289             Ben Maillot
320        1249         Isabel Pruschke
321        5409        Linda Franceschi
322        2951        Olivia Striebitz
323        3432            Penny Watson
324        2297           Manfred James
325        6161            Hazel Pierce
326        4603               Alf Bates
327        5818             Scott Gough
328        4270          Konrad Briones
329        6007     Mathilde Kruschwitz
330        4084             Irma Gemito
331        1340           Antoine Guyon
332        5675       William Gibilisco
333        2010            Judith Butte
334        6201        Joanne Henderson
335        1791       Ludovica Arellano
336        3314          Catherine Gray
337        5852       Franco Fioravanti
338        4618          Heather Zimmer
339        2618         Hortense Taylor
340        4967             Livia Ernst
341        4594             Toby Etzler
342        2080       Ennio Leoncavallo
343        2793         Philippine Vaca
344        4890         Rhonda Phillips
345        3528          Alphonse Nitto
346        5810          Karina Arreola
347        5720             Denise Wood
348        4593        Burghard Rosenow
349        3186           Friedl Powell
350        5136        Benjamin Schultz
351        2646         Rachel Ulibarri
352        3460        Silvano Blanchet
353        4345              Kurt Sauer
354        2690        Nayeli Gehringer
355        4025           Imelda Guerin
356        4524         Zbigniew Holmes
357        3978           Adela Alfonsi
358        3910            Hilary Clark
359        5825        Kornelius Molina
360        3564      Christian Anderson
361        2396        Francisco Dorsey
362        2140            Walli Albert
363        3079            Siegrun Mota
364        2017          Alberico Herve
365        5444         Serafina Bonnin
366        2216         Marcelle Bender
367        1241      Hartmuth Robertson
368        1484         Herlinde George
369        3475            Pamela Payne
370        4333           Gastone Beyer
371        5657        Lydia Berengario
372        2527           Lucy Davidson
373        5967             Franck Wade
374        5698            Heidi Barker
375        3331          Arnaldo Ocasio
376        3841         Francis Bernier
377        6105          Johanne Strong
378        3895          Debra Langlois
379        1891          Reingard Kambs
380        1281             Mauro Ortiz
381        4186       Griselda Carranza
382        2511          Janet Madrigal
383        4272               Jenna Day
384        3533          Modesto Wright
385        3618              Alice Wall
386        2177           Brenda Sontag
387        4102            Sergius Mace
388        6089           Antonia Kline
389        4701        Maurice Gumprich
390        5645           Daniel Anders
391        4499          Zaira Cattaneo
392        3365         Alessio Bruneau
393        2290          Gerdi Guerrero
394        1890       Brigitte Stiebitz
395        1304             June Sinisi
396        3799             Carl Macias
397        2749          Veronica Trapp
398        2028         Frances Garnier
399        2383          Terri Iannelli
400        5721            Odette Moore
401        1394       Mercedes Trujillo
402        3451           Babette Dumas
403        5512          Jerry Santiago
404        2453          Ronald Simpson
405        6055      Emmanuel Dominguez
406        5704    Christiane Ricciardi
407        3707           Ingolf Zamora
408        2205              Rita Sharp
409        5976       Geraldine Cabrera
410        3290           Chantal Armas
411        4257           Louis Gilbert
412        4588        Michelle Collier
413        4785   Guillermina Nicholson
414        3033        Bertrand Hopkins
415        2779           Alonso Palomo
416        2131          Tina Rodriguez
417        6229             Eva Francis
418        3429            Ottavio Rust
419        1613           Amelia Olvera
420        4734           Paul Palladio
421        4439        Bernardo Wieloch
422        1441           Umberto Hicks
423        5799            Janko Bishop
424        1419         Jessika Meunier
425        3059            Isaac Benard
426        3224      Alexandrie Lambert
427        3181           Roberto Guyot
428        6061         Giulietta Lucas
429        4466     Damaris Pininfarina
430        6081         Fabrizia Renard
431        2159          Camillo Dehmel
432        3324        Ruggero Parpinel
433        3176         Stephen Pratesi
434        5874          Ludger Naccari
435        5110            Meryem Tapia
436        5490          Jasmine Juvara
437        1922      Victoire Travaglia
438        4398             Adrian Noel
439        4754             Marvin Howe
440        3309              Hanne Kidd
441        1244        Donatello Millet
442        2892       Eloisa Pascarella
443        2777          Erica Zambrano
444        4952           Paula Canales
445        5144         Claudia Bernard
446        5487          Paulina Miller
447        1932         Kathrin Godfrey
448        3364        Pina Passalacqua
449        5165            Julien Miles
450        3858         Suzanne Benigni
451        4666           Annalisa Pugh
452        2896          Mathew Maestas
453        4520           Laszlo Vallee
454        5726           Helen Polanco
455        5661        Mateo Sorrentino
456        4765             Eric Barnes
457        3710            Dragica West
458        4925            Antje Voisin
459        1533           Stanley Mills
460        5264            Brandy Meraz
461        4606         Conor Reinhardt
462        2043             Gabino Blot
463        3871            Alvaro Lemus
464        6205          Patrizia Wilms
465        3193            Metin Coulon
466        1810          Reece Valencia
467        4797        Troy Schmiedecke
468        1487            Wendy Bustos
469        3474      Guglielmo Caldwell
470        5771            Travis Cowan
471        6074        Brandi Abbagnale
472        1568            Hanno Gollum
473        4263             Jutta Burke
474        5850             Dorothe Paz
475        5619          Desiree Huerta
476        1904               Ilse Bray
477        5388       Pierpaolo Scaduto
478        2150         Amedeo Bradford
479        2653               Julia Ali
480        2687       Catalina Pizzetti
481        3779            Dylan Porzio
482        1494        Iris Trincavelli
483        4129      Johnathan Guidotti
484        3035     Walburga Vollbrecht
485        2069            Kendra David
486        5469         Aleksandr Weiss
487        3903       Cornelio Guardado
488        4083         Ferdi Blackburn
489        4003          Bill Gallagher
490        3565          Leonard Harvey
491        1640        Milan Montenegro
492        4769            Philip Perez
493        3398       Kathryn Hentschel
494        1865           Xavier Samson
495        5690         Hartwig Roberts
496        3814           Kimberly Chan
497        2942       Lorraine Crawford

In [32]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.
contact_info_df_copy_df = pd.DataFrame({"contact_id": contact_info_df_copy['contact_id'], 
                                        "name": contact_info_df_copy['name'], 
                                        "email":contact_info_df_copy['email']})

contact_info_df_copy_df.head(10)

   contact_id               name                         email
0        4661    Cecilia Velasco  cecilia.velasco@rodrigues.fr
1        3765      Mariana Ellis       mariana.ellis@rossi.org
2        4187        Sofie Woods       sofie.woods@riviere.com
3        4941  Jeanette Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel Sorgatz      samuel.sorgatz@gmail.com
5        5650       Socorro Luna      socorro.luna@hotmail.com
6        5889    Carolina Murray    carolina.murray@knight.com
7        4842         Kayla Moon           kayla.moon@yahoo.de
8        3280     Ariadna Geisel     ariadna.geisel@rangel.com
9        5468    Danielle Ladeck  danielle.ladeck@scalfaro.net

In [33]:
contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy_df['name'].str.split(" ", 1, expand=True)
contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy_df['name'].str.split(' ', 1).str
contact_info_df_copy_df.head()

C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\1818741694.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy_df['name'].str.split(" ", 1, expand=True)
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\1818741694.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy_df['name'].str.split(' ', 1).str
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\1818741694.py:2: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy_df['name'].str.split(' ', 1).str

,contact_id,name,email,first_name,last_name
0,4661,Cecilia Velasco,cecilia.velasco@rodrigues.fr,Cecilia,Velasco
1,3765,Mariana Ellis,mariana.ellis@rossi.org,Mariana,Ellis
2,4187,Sofie Woods,sofie.woods@riviere.com,Sofie,Woods
3,4941,Jeanette Iannotti,jeanette.iannotti@yahoo.com,Jeanette,Iannotti
4,2199,Samuel Sorgatz,samuel.sorgatz@gmail.com,Samuel,Sorgatz

In [35]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy['name'].str.split(" ", 1, expand=True)
contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy['name'].str.split(' ', 1).str
contact_info_df_copy_df.head(10)

# Drop the contact_name column
contact_info_df_copy_df = contact_info_df_copy_df.drop('name', axis=1)
contact_info_df_copy_df.head(10)

C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\186885466.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy['name'].str.split(" ", 1, expand=True)
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\186885466.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy['name'].str.split(' ', 1).str
C:\Users\Kalyn\AppData\Local\Temp\ipykernel_20548\186885466.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  contact_info_df_copy_df['first_name'], contact_info_df_copy_df['last_name'] = contact_info_df_copy['name'].str.split(' ', 1).str

KeyError: "['name'] not found in axis"

In [ ]:
# Reorder the columns
contacts_df_clean = pd.DataFrame({"contact_id": contact_info_df_copy_df['contact_id'], 
                                        "first_name": contact_info_df_copy_df['first_name'], 
                                        "last_name": contact_info_df_copy_df['last_name'],
                                        "email":contact_info_df_copy['email']})

contacts_df_clean.head(10)

In [ ]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.info()

In [36]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)